### ISSUE TITLE
Add the Docker image with Taurus to a docker-compose workspace

### ISSUE THREAD

**Issue by LJBD** [synchrotron-solaris/cfg-solaris-docker-taurus#2]
The image prepared as a part of #1 should be integrated in a docker-compose workspace with the following containers:
- [x] mariadb - with a MariaDB MySQL database; you can use the version of `mariadb-server` that's available in yum repositories
- [x] tango-db - with a Tango DatabaseDS
- [x] tango-ds - with a client version of Tango, launching Tango Test at startup
- [x] tango-taurus - with Tango & Taurus.

**Comment by wkitka** [comment]
Also, please bear in mind that you'll need some additional libraries for your Device Classes (e.g. a Modbus library, `facadedevice`, etc.). You might want to update the existing image so that it has those libraries as well.

**Comment by stanislaw47** [comment]
In which container should we install those libraries? Tango-Test or Taurus-Test?

**Comment by LJBD** [comment]
You should install them where you'll launch the DS - so in Tango-Test.

**Comment by daneos** [comment]
It would also be nice to have a container with Sardana and sar-demo configured.

**Comment by LJBD** [comment]
@daneos - I've already done it :)
